### ISSUE TITLE
Feature Request: Expose Scalar Multiplication or No-Fail Scalar Inversion

### ISSUE THREAD

**Issue by jeffro256** [tevador/mx25519#9]
`mx25519_invkey` has a tiny chance to fail randomly. To make a guaranteed no-fail version (albeit with more overhead), @UkoeHB created a wrapper which keeps adding eights to the inversion scalars until it succeeds, multiplying the resulting pub-key by eights as well to cancel out the inverted eights. You can see it here: https://github.com/UkoeHB/monero/blob/ea9fa079bf0ce0a6d32472801db8d58bfbf0276a/src/crypto/x25519.cpp#L104-L116. However, the `mx25519` API doesn't allow this to be done if I didn't want to multiply against an initial pubkey since I can't multiply scalars directly.

The context:
For Jamtis balance recovery, I created a cache to speed up one-time address recomputation given an nominal address tag and stored account information. Since the address private key and unlock amounts private key are both constant for a given index, this means that the value `1 / (k^j_a * k_ua)` is constant for a given index as well. If we cache this value, as well as the spendkey extensions, and address spendkey, then we can skip the inverse Diffie-Helman operation and 3 scalar multiplication-add operations per possibly owned enote. This would benefit users who receive a lot of plain enotes to the same public address (e.g. charities, CCS General Fund, users of basic wallets which only generate one address) or users with a lot of send-sends (e.g. customers, churners).

To calculate the value `1 / (k^j_a * k_ua)` in a no-fail manner similar to how @UkoeHB did it in the above code snippet, we would need API access to scalar multiplication or a no-fail version of `mx25519_invkey`.

**Comment by UkoeHB** [comment]
>  I created a cache to speed up one-time address recomputation given an nominal address tag and stored account information. Since the address private key and unlock amounts private key are both constant for a given index, this means that the value 1 / (k^j_a * k_ua) is constant for a given index as well. If we cache this value, as well as the spendkey extensions, and address spendkey, then we can skip the inverse Diffie-Helman operation and 3 scalar multiplication-add operations per possibly owned enote.

Since all of these computations occur after the view tag check(s), optimizing them out has negligible impact on balance recovery time.  Even for users with many owned enotes, the boat-load of elliptic curve operations involved in post-filtering balance recovery far outweigh these scalar operations. I recommend either dropping the cache, or if you think it is worthwhile then benchmarking to show that I am wrong and it does accomplish something (and to justify changes to this library).

**Comment by jeffro256** [comment]
Yeah you were right, it didn't end up being worth it. Was marginally faster if the user owned a larger percentage of the enotes, but didn't really affect total scan time.
